language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
script:
- gulp lint && gulp publish
after_success:
- ./bin/versionz.js -q && touch RELEASE
deploy:
  provider: npm
  email: aeoliant@gmail.com
  api_key:
    secure: nYax3/nzfN/a3+eOpk1+p6x3pgaXHVUO0hYzHw5AyHKKF7Ed28x/lbLeNB8xh3c3OgiHUWuy+ImpNs3e3wc9dwsC5oogM6GVMI/b6146yak1jgECD0pTxMqUl4Hg+GzPB/En6WoNB1IouVNMF1ORySHkGYJFiAGE0VZ5sTegqec=
  on:
    repo: aeoliant/versionz
    condition: "-f RELEASE"
